build:
  - ".github/**/*"
  - ".coveralls.yml"
  - ".styleci.yml"
  - ".gitignore"
  - ".gitattributes"
  - ".editorconfig"

dependencies:
  - "composer.json"
  - "composer.lock"

common:
  - "src/**/*"

docs:
  - "README.md"
  - "LICENSE.md"
  - "CONTRIBUTING.md"