build:
  - ".github/**/*"
  - ".coveralls.yml"
  - ".styleci.yml"
  - ".gitignore"
  - ".gitattributes"
  - ".editorconfig"

dependencies:
  - "composer.json"
  - "composer.lock"

common:
  - "src/**/*"

tests:
  - "tests/**/*"
  - "phpunit.xml.dist"
  - "phpstan.neon.dist"

docs:
  - "README.md"
  - "LICENSE.md"
  - "CONTRIBUTING.md"