version-template: "$MAJOR.$MINOR.$PATCH"
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '✨ Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'common'

  - title: '🐞 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'hotfix'
  
  - title: '📦 Dependencies'
    labels:       
      - 'dependencies'
  
  - title: '🏗️ Maintenance'
    labels:
      - 'chore'
      - 'build'
  
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking'

  - title: '♻️ Refactoring'
    labels:
      - 'refactoring'
  
  - title: '🧪 Tests'
    labels:
      - 'tests'
  
  - title: '📖 Docs'
    labels:
      - 'docs'

  - title: '💡 Todo'
    labels:
      - 'todo'

change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - major
      - breaking
      - refactoring
  minor:
    labels:
      - feature
      - enhancement
      - minor
      - common
  patch:
    labels:
      - patch
      - build
      - bug
      - bugfix
      - hotfix
      - fix
      - docs
      - tests
  default: patch

change-template: '- #$NUMBER: $TITLE'
template: |
  ## Changes
  
  $CHANGES