template: |
  ## Changes
  $CHANGES
change-template: '- **$TITLE** (#$NUMBER)'

version-template: "$MAJOR.$MINOR.$PATCH"
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '✨ Features'
      labels:
        - 'feature'
        - 'enhancement'
        - 'common'

  - title: '🐞 Bug Fixes'
      labels:
        - 'fix'
        - 'bugfix'
        - 'bug'
        - 'hotfix'
  
  - title: '📦 Dependencies'
      labels:       
        - 'dependencies'
  
  - title: '🏗️ Maintenance'
      labels:
        - 'chore'
        - 'build'
  
  - title: '♻️ Refactoring'
      labels:
        - 'refactoring'
  
  - title: '🧪 Tests'
      labels:
        - 'tests'
  
  - title: '📖 Docs'
      labels:
        - 'docs'

change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - major
      - refactoring
  minor:
    labels:
      - feature
      - enhancement
      - minor
      - common
  patch:
    labels:
      - patch
      - build
      - bug
      - bugfix
      - hotfix
      - fix
      - docs
      - tests
  default: patch